spring:
  profiles: dev
  application:
    name: spring-cloud-config-dev

---

spring:
  profiles: test
  application:
    name: spring-cloud-config-test

---

spring:
  profiles: proc
  application:
    name: spring-cloud-config-proc


